### ISSUE TITLE
Update CLA process to match new requirements from NumFOCUS

### ISSUE THREAD

**Issue by jezdez** [conda/infrastructure#932]
### Checklist

- [X] I added a descriptive title
- [X] I searched open issues and couldn't find a duplicate

### What?

The CLA process under NumFOCUS will require keeping a `.cla_signers` file in every repo in the conda organization.

### Why?

Here's an excerpt from the new CLA (bold for noting):

>  In case you're new to CLAs, this is rather standard procedure for larger projects.[ Django](https://www.djangoproject.com/foundation/cla/) and even[ Python](https://www.python.org/psf/contrib/contrib-form/) itself both use something similar.
> 
> ## Process
>
> New contributors should complete the Conda Contributor License Agreement located[ here](https://conda.io/en/latest/contributing.html#conda-contributor-license-agreement). A signed contributor license agreement for a pull request author needs to be on file with NumFOCUS, Inc. for pull requests to be merged. **A record of signatories is kept in the .cla-signers file in the project root.**
>
> ## Individual Contributor License Agreement – Conda Code Organization
> In order to clarify the intellectual property license granted with Contributions from any person or entity, **all projects under the Conda Code Organization (“Conda”) must have a Contributor License Agreement (“Agreement”) on file that has been signed by each Contributor, indicating agreement to the license terms below for each project**. This license is for your protection as a Contributor as well as the protection of NumFOCUS, Inc. (“NumFOCUS”) as the legal entity of Conda, and Anaconda, Inc. (“Anaconda”); it does not change your rights to use your own Contributions for any other purpose. **This agreement applies to any current and all future Conda projects, including conda, conda-build, constructor, and associated projects under the Conda Code Organization.** While currently hosted on GitHub at[ https://github.com/conda](https://github.com/conda), the project hosting site is subject to change at the sole discretion of Conda’s leadership as stated in their governance.

### User impact

Contributors must be able to sign the new CLA only once, enabling them to contribute to any of the projects under the conda organization.

### Goals

- [ ] Sunset Anaconda CLA process
- [ ] Start of NumFOCUS CLA process
- [ ] Update the community about the changes

### Tasks

- [ ] Create a new `CLA reviewer` team (which is an official conda governance subteam)
- [ ] On every PR check if the PR author has signed the CLA against a central list of signers (in `conda/infrastructure` under `cla/signers.json`)
- [ ] Require contributor to sign the PDF hosted under the NumFOCUS Adobe Sign account
- [ ] Open a PR in `conda/infrastructure` that adds the contributor to the central `cla/signers.json`
	- Automatically assigns the PR to the `CLA reviewer` team
- [ ] Copy the updated `cla/signers.json` file to all repos under the conda organization
	- The mode of copying can either be push as-is, or by pull via https://github.com/conda/actions/pull/127

### This epic is blocked by:

- [ ] https://github.com/conda/actions/pull/127

### This epic blocks:

- [ ] https://github.com/conda/conda-docs/issues/931

**Comment by jezdez** [comment]
@conda/steering-council FYI, I've started to work on this process.
